Photo validation (size and resoulution)
ita-social-projects/TeachUA pull request #1029
Opened 2021-11-01 18:01 UTC by OH72

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-11-01 18:02 UTC, OH72 commented on src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> +            throw new IncorrectInputException(String.format(IMAGE_SIZE_EXCEPTION, IMAGE_SIZE_B, multipartFile.getSize()));
throw exception if size is larger than allowed

2021-11-01 18:02 UTC, OH72 commented on src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> +                throw new IncorrectInputException(String.format(IMAGE_RESOLUTION_EXCEPTION, "height", height));
throw exception if height is smaller than allowed

2021-11-01 18:02 UTC, OH72 commented on src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> +                throw new IncorrectInputException(String.format(IMAGE_RESOLUTION_EXCEPTION, "width", width));
throw exception if widthis smaller than allowed

2021-11-01 18:03 UTC, OH72 commented on src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> +    private static final Long MIN_IMAGE_HEIGHT = 200L;
allowed constants

2021-11-01 18:03 UTC, OH72 commented on src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> +    private final String IMAGE_RESOLUTION_EXCEPTION = "Image %s should be more than %d";
exception messages

2021-11-02 07:34 UTC, VictoriaAmazonka requested changes
e.printStackTrace(); -we have to use logger to log messages.

2021-11-02 07:39 UTC, OH72 commented
> 
> 
> e.printStackTrace(); -we have to use logger to log messages.

I replaced it with log.error.

2021-11-02 07:46 UTC, VictoriaAmazonka approved these changes

2021-11-02 07:49 UTC, merged