Review upload
ita-social-projects/TeachUA pull request #1087
Opened 2021-11-09 11:01 UTC by vitalik12345678

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-11-09 11:05 UTC, vitalik12345678 commented on src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> +        Optional<Club> optionalClub = clubRepository.findById(id);
DB add

2021-11-09 11:05 UTC, vitalik12345678 commented on src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> +    private void saveFile(String uploadDir, String fileName, MultipartFile multipartFile) {
Method for save file on hard disk

2021-11-09 11:05 UTC, vitalik12345678 commented on src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> +    private void delete(String filePath){
Method for delete file from disk

2021-11-09 11:05 UTC, vitalik12345678 commented on src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> +    public String updatePhoto(MultipartFile file,String filePath,String uploadDirectory) {
We saveing the file from disk after delete and changed url to bd

2021-11-10 11:18 UTC, VictoriaAmazonka requested changes
Post and request params….

2021-11-11 18:03 UTC, closed without merging