Comparing incorrect address
ita-social-projects/TeachUA pull request #1187
Opened 2021-11-28 21:25 UTC by RostFromLv

Controller for fixing incorrect address in DB

2021-11-29 09:54 UTC, VictoriaAmazonka requested changes

2021-11-29 09:54 UTC, VictoriaAmazonka commented on src/main/java/com/softserve/teachua/controller/AddressController.java
> +    @PreAuthorize("hasAnyRole(T(com.softserve.teachua.constants.RoleData).ADMIN.getDBRoleName())")
We have our new annotation https://github.com/ita-social-projects/TeachUA/pull/1155/files

2021-11-29 09:54 UTC, VictoriaAmazonka commented on src/main/java/com/softserve/teachua/service/impl/AddressServiceImpl.java
> +                System.out.println(city.getName()+": "+true);
Use logger please

2021-11-29 09:54 UTC, VictoriaAmazonka commented on src/main/java/com/softserve/teachua/service/impl/AddressServiceImpl.java
> +            if (( address.contains(city.getName())  &&  (address.matches(".*("+city.getName()+"[^а-яА-ЯіІїЇєЄ]+).*")) )
Could you explain what you do here?

2021-11-29 16:55 UTC, RostFromLv commented on src/main/java/com/softserve/teachua/controller/AddressController.java
> +    @PreAuthorize("hasAnyRole(T(com.softserve.teachua.constants.RoleData).ADMIN.getDBRoleName())")
I didn`t know about this annotation.

2021-11-29 16:57 UTC, RostFromLv commented on src/main/java/com/softserve/teachua/service/impl/AddressServiceImpl.java
> +                System.out.println(city.getName()+": "+true);
I don`t know about logger, because this controller for 1 time-use

2021-11-29 17:01 UTC, RostFromLv commented on src/main/java/com/softserve/teachua/service/impl/AddressServiceImpl.java
> +            if (( address.contains(city.getName())  &&  (address.matches(".*("+city.getName()+"[^а-яА-ЯіІїЇєЄ]+).*")) )
Ok, here i`m check: 
1.Have our address text  CITY 
2.If have, is it clear city or word with containing this city( street  "КИЇВська" or "ЛЬВІВська")

2021-11-30 10:34 UTC, VictoriaAmazonka approved these changes
There is one more System.out. Delete in te

2021-11-30 10:35 UTC, merged