Upgraded log functional
ita-social-projects/TeachUA pull request #1234
Opened 2021-12-13 17:45 UTC by RostFromLv

Added JavaDoc to log controller
Refactored log services

2021-12-14 18:25 UTC, VictoriaAmazonka approved these changes

2021-12-14 18:26 UTC, VictoriaAmazonka requested changes

2021-12-14 18:26 UTC, VictoriaAmazonka commented on src/main/java/com/softserve/teachua/service/impl/LogServiceImpl.java
> +                                e.printStackTrace();
Please, change to logger

2021-12-14 18:30 UTC, VictoriaAmazonka requested changes

2021-12-14 18:30 UTC, VictoriaAmazonka commented on src/main/java/com/softserve/teachua/service/impl/LogServiceImpl.java
> -        return "Created sub directory in logs with name: "+file.getName();
It’s wrong design to return status in this String

2021-12-14 20:49 UTC, RostFromLv commented on src/main/java/com/softserve/teachua/service/impl/LogServiceImpl.java
> +                                e.printStackTrace();
This line was deleted in next commit in this merge

2021-12-17 16:21 UTC, VictoriaAmazonka approved these changes

2021-12-17 21:25 UTC, merged