Fixed PATCH /api/club/{id} endpoint is not performing direct function of updating club
ita-social-projects/TeachUA pull request #1603
Opened 2023-01-04 13:07 UTC by litvinchuck

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-01-04 13:20 UTC, Vekeryk requested changes

2023-01-04 13:20 UTC, Vekeryk commented on src/main/java/com/softserve/teachua/controller/ClubController.java
> +    @AllowedRoles({ RoleData.ADMIN, RoleData.USER })
Only ADMIN and MANAGER can create club, so only they can put and patch

2023-01-04 13:26 UTC, litvinchuck commented on src/main/java/com/softserve/teachua/controller/ClubController.java
> +    @AllowedRoles({ RoleData.ADMIN, RoleData.USER })
👍

2023-01-04 14:35 UTC, BNazar002 approved these changes

2023-01-04 15:09 UTC, Vekeryk approved these changes

2023-01-05 09:04 UTC, softservedata approved these changes

2023-01-05 09:04 UTC, merged