[Test Coverage] Test ChallengeService #1619
ita-social-projects/TeachUA pull request #1626
Opened 2023-01-15 22:18 UTC by GVVlad

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-01-16 08:00 UTC, Vekeryk requested changes

2023-01-16 08:00 UTC, Vekeryk commented on src/test/java/com/softserve/teachua/service/ChallengeServiceTest.java
> +            .thenReturn(successUpdatedChallenge);
Here you return successUpdatedChallenge

2023-01-16 08:00 UTC, Vekeryk commented on src/test/java/com/softserve/teachua/service/ChallengeServiceTest.java
> +            .isEqualTo(successUpdatedChallenge);
And here you check if it equals  successUpdatedChallenge. I think it would be better to check  if your challenge object really have updated fields. You can use ArgumentCaptor on challengeRepository.save().

And you don't actually need mock challengeRepository.save() and dtoConverter.convertToDto(), just verify that these methods were called

2023-01-16 08:00 UTC, Vekeryk commented on src/test/java/com/softserve/teachua/service/ChallengeServiceTest.java
> +        when(challengeRepository.save(challenge))
Same on update here, use ArgumentCaptor

2023-01-16 08:00 UTC, Vekeryk commented on src/test/java/com/softserve/teachua/service/ChallengeServiceTest.java
> +        when(dtoConverter.convertToDto(challenge, ChallengeArch.class))
You already have tested archiveModel(challenge), so try to do not mock logic inside this method, use doNothing on archiveModel(challenge)

2023-01-16 08:00 UTC, Vekeryk commented on src/test/java/com/softserve/teachua/service/ChallengeServiceTest.java
> +    void getChallengeTest() {
You also should test case with NotExistException

2023-01-17 09:04 UTC, softservedata approved these changes

2023-01-17 09:06 UTC, BNazar002 approved these changes

2023-01-17 09:06 UTC, Vekeryk approved these changes

2023-01-17 10:07 UTC, merged