Added functionality to count rate of center
ita-social-projects/TeachUA pull request #1782
Opened 2023-06-15 09:40 UTC by NadiiaNanivska

Added a new endpoint in the CenterController to retrieve all clubs by center ID.
Updated the ClubRepository to include a method for retrieving all clubs by center ID.
Expanded the CenterService with method to retrieve list of all clubs.
Implemented method in the CenterServiceImpl to fetch clubs by center ID.

2023-06-17 19:21 UTC, BNazar00 commented on src/main/java/com/softserve/teachua/controller/CenterController.java
> +    public Object getCenterClubsByCenterId(@PathVariable Long id,
Consider using more specific return types. The method's return type is currently defined as `Object`, I'd not recommend doing so.

2023-06-17 19:21 UTC, BNazar00 requested changes
First of all, please ensure that you have familiarized yourself with the pull request template, which you seem to have deleted. It is crucial to retain the 'Checklist' section and indicate the items that are necessary.

Additionally, it would be immensely helpful if you could provide a brief description of your pull request. If you have resolved an issue, mention it and include a link to the corresponding issue for reference (if such is) or shortly describe what you've fixed.

Furthermore, I kindly request that you address the comment from SonarBot on your pull request. It is essential to make an effort to avoid introducing any new issues. Presently, there is one 'Code Smell' that requires attention. The SonarBot comment provides further details regarding this matter.

2023-06-17 20:14 UTC, NadiiaNanivska commented on src/main/java/com/softserve/teachua/controller/CenterController.java
> +    public Object getCenterClubsByCenterId(@PathVariable Long id,
Done

2023-06-18 09:17 UTC, BNazar00 requested changes

2023-06-18 09:17 UTC, BNazar00 commented on src/main/java/com/softserve/teachua/controller/CenterController.java
> +    public Object getAllCenterClubsByCenterId(@PathVariable Long id) {
Regarding the return type, please see my previous comment for the suggestion of using a more specific return type.

2023-06-18 09:17 UTC, BNazar00 commented on src/main/java/com/softserve/teachua/controller/CenterController.java
> +    public Object getAllCenterClubsByCenterId(@PathVariable Long id) {
I'd also highly recommend following the project's API routes convention. If you have chosen to associate this functionality with the `CenterController` and there is a similar route, consider using the parameter, like
 ```suggestion
     @GetMapping("/centers/clubs", params = "centerId")
     public Object getAllCenterClubsByCenterId(@RequestParam("centerId) Long id) {
```


I'd relate such functionality to `ClubController`, though.

2023-06-18 17:44 UTC, closed without merging